/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthAtChar123workspaceSlugChar125RouteImport } from './routes/_auth/@{$workspaceSlug}'
import { Route as AuthOrganizationsIndexRouteImport } from './routes/_auth/organizations/index'
import { Route as AuthAtChar123workspaceSlugChar125IndexRouteImport } from './routes/_auth/@{$workspaceSlug}/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAtChar123workspaceSlugChar125ResourceSlugRouteImport } from './routes/_auth/@{$workspaceSlug}/$resourceSlug'
import { Route as AuthAtChar123workspaceSlugChar125ResourceSlugIndexRouteImport } from './routes/_auth/@{$workspaceSlug}/$resourceSlug/index'
import { Route as AuthAtChar123workspaceSlugChar125Char126SettingsRouteImport } from './routes/_auth/@{$workspaceSlug}/~/settings'
import { Route as AuthAtChar123workspaceSlugChar125Char126MembersRouteImport } from './routes/_auth/@{$workspaceSlug}/~/members'
import { Route as AuthAtChar123workspaceSlugChar125Char126BillingRouteImport } from './routes/_auth/@{$workspaceSlug}/~/billing'
import { Route as AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRouteImport } from './routes/_auth/@{$workspaceSlug}/$resourceSlug/~/settings'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAtChar123workspaceSlugChar125Route =
  AuthAtChar123workspaceSlugChar125RouteImport.update({
    id: '/@{$workspaceSlug}',
    path: '/@{$workspaceSlug}',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOrganizationsIndexRoute = AuthOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAtChar123workspaceSlugChar125IndexRoute =
  AuthAtChar123workspaceSlugChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAtChar123workspaceSlugChar125Route,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAtChar123workspaceSlugChar125ResourceSlugRoute =
  AuthAtChar123workspaceSlugChar125ResourceSlugRouteImport.update({
    id: '/$resourceSlug',
    path: '/$resourceSlug',
    getParentRoute: () => AuthAtChar123workspaceSlugChar125Route,
  } as any)
const AuthAtChar123workspaceSlugChar125ResourceSlugIndexRoute =
  AuthAtChar123workspaceSlugChar125ResourceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAtChar123workspaceSlugChar125ResourceSlugRoute,
  } as any)
const AuthAtChar123workspaceSlugChar125Char126SettingsRoute =
  AuthAtChar123workspaceSlugChar125Char126SettingsRouteImport.update({
    id: '/~/settings',
    path: '/~/settings',
    getParentRoute: () => AuthAtChar123workspaceSlugChar125Route,
  } as any)
const AuthAtChar123workspaceSlugChar125Char126MembersRoute =
  AuthAtChar123workspaceSlugChar125Char126MembersRouteImport.update({
    id: '/~/members',
    path: '/~/members',
    getParentRoute: () => AuthAtChar123workspaceSlugChar125Route,
  } as any)
const AuthAtChar123workspaceSlugChar125Char126BillingRoute =
  AuthAtChar123workspaceSlugChar125Char126BillingRouteImport.update({
    id: '/~/billing',
    path: '/~/billing',
    getParentRoute: () => AuthAtChar123workspaceSlugChar125Route,
  } as any)
const AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRoute =
  AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRouteImport.update(
    {
      id: '/~/settings',
      path: '/~/settings',
      getParentRoute: () => AuthAtChar123workspaceSlugChar125ResourceSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/@{$workspaceSlug}': typeof AuthAtChar123workspaceSlugChar125RouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/@{$workspaceSlug}/$resourceSlug': typeof AuthAtChar123workspaceSlugChar125ResourceSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/@{$workspaceSlug}/': typeof AuthAtChar123workspaceSlugChar125IndexRoute
  '/organizations/': typeof AuthOrganizationsIndexRoute
  '/@{$workspaceSlug}/~/billing': typeof AuthAtChar123workspaceSlugChar125Char126BillingRoute
  '/@{$workspaceSlug}/~/members': typeof AuthAtChar123workspaceSlugChar125Char126MembersRoute
  '/@{$workspaceSlug}/~/settings': typeof AuthAtChar123workspaceSlugChar125Char126SettingsRoute
  '/@{$workspaceSlug}/$resourceSlug/': typeof AuthAtChar123workspaceSlugChar125ResourceSlugIndexRoute
  '/@{$workspaceSlug}/$resourceSlug/~/settings': typeof AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/@{$workspaceSlug}': typeof AuthAtChar123workspaceSlugChar125IndexRoute
  '/organizations': typeof AuthOrganizationsIndexRoute
  '/@{$workspaceSlug}/~/billing': typeof AuthAtChar123workspaceSlugChar125Char126BillingRoute
  '/@{$workspaceSlug}/~/members': typeof AuthAtChar123workspaceSlugChar125Char126MembersRoute
  '/@{$workspaceSlug}/~/settings': typeof AuthAtChar123workspaceSlugChar125Char126SettingsRoute
  '/@{$workspaceSlug}/$resourceSlug': typeof AuthAtChar123workspaceSlugChar125ResourceSlugIndexRoute
  '/@{$workspaceSlug}/$resourceSlug/~/settings': typeof AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_auth/@{$workspaceSlug}': typeof AuthAtChar123workspaceSlugChar125RouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/@{$workspaceSlug}/$resourceSlug': typeof AuthAtChar123workspaceSlugChar125ResourceSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/@{$workspaceSlug}/': typeof AuthAtChar123workspaceSlugChar125IndexRoute
  '/_auth/organizations/': typeof AuthOrganizationsIndexRoute
  '/_auth/@{$workspaceSlug}/~/billing': typeof AuthAtChar123workspaceSlugChar125Char126BillingRoute
  '/_auth/@{$workspaceSlug}/~/members': typeof AuthAtChar123workspaceSlugChar125Char126MembersRoute
  '/_auth/@{$workspaceSlug}/~/settings': typeof AuthAtChar123workspaceSlugChar125Char126SettingsRoute
  '/_auth/@{$workspaceSlug}/$resourceSlug/': typeof AuthAtChar123workspaceSlugChar125ResourceSlugIndexRoute
  '/_auth/@{$workspaceSlug}/$resourceSlug/~/settings': typeof AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/@{$workspaceSlug}'
    | '/dashboard'
    | '/profile'
    | '/@{$workspaceSlug}/$resourceSlug'
    | '/api/auth/$'
    | '/@{$workspaceSlug}/'
    | '/organizations/'
    | '/@{$workspaceSlug}/~/billing'
    | '/@{$workspaceSlug}/~/members'
    | '/@{$workspaceSlug}/~/settings'
    | '/@{$workspaceSlug}/$resourceSlug/'
    | '/@{$workspaceSlug}/$resourceSlug/~/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/dashboard'
    | '/profile'
    | '/api/auth/$'
    | '/@{$workspaceSlug}'
    | '/organizations'
    | '/@{$workspaceSlug}/~/billing'
    | '/@{$workspaceSlug}/~/members'
    | '/@{$workspaceSlug}/~/settings'
    | '/@{$workspaceSlug}/$resourceSlug'
    | '/@{$workspaceSlug}/$resourceSlug/~/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/pricing'
    | '/_auth/@{$workspaceSlug}'
    | '/_auth/dashboard'
    | '/_auth/profile'
    | '/_auth/@{$workspaceSlug}/$resourceSlug'
    | '/api/auth/$'
    | '/_auth/@{$workspaceSlug}/'
    | '/_auth/organizations/'
    | '/_auth/@{$workspaceSlug}/~/billing'
    | '/_auth/@{$workspaceSlug}/~/members'
    | '/_auth/@{$workspaceSlug}/~/settings'
    | '/_auth/@{$workspaceSlug}/$resourceSlug/'
    | '/_auth/@{$workspaceSlug}/$resourceSlug/~/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/@{$workspaceSlug}': {
      id: '/_auth/@{$workspaceSlug}'
      path: '/@{$workspaceSlug}'
      fullPath: '/@{$workspaceSlug}'
      preLoaderRoute: typeof AuthAtChar123workspaceSlugChar125RouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/': {
      id: '/_auth/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthOrganizationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/@{$workspaceSlug}/': {
      id: '/_auth/@{$workspaceSlug}/'
      path: '/'
      fullPath: '/@{$workspaceSlug}/'
      preLoaderRoute: typeof AuthAtChar123workspaceSlugChar125IndexRouteImport
      parentRoute: typeof AuthAtChar123workspaceSlugChar125Route
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/@{$workspaceSlug}/$resourceSlug': {
      id: '/_auth/@{$workspaceSlug}/$resourceSlug'
      path: '/$resourceSlug'
      fullPath: '/@{$workspaceSlug}/$resourceSlug'
      preLoaderRoute: typeof AuthAtChar123workspaceSlugChar125ResourceSlugRouteImport
      parentRoute: typeof AuthAtChar123workspaceSlugChar125Route
    }
    '/_auth/@{$workspaceSlug}/$resourceSlug/': {
      id: '/_auth/@{$workspaceSlug}/$resourceSlug/'
      path: '/'
      fullPath: '/@{$workspaceSlug}/$resourceSlug/'
      preLoaderRoute: typeof AuthAtChar123workspaceSlugChar125ResourceSlugIndexRouteImport
      parentRoute: typeof AuthAtChar123workspaceSlugChar125ResourceSlugRoute
    }
    '/_auth/@{$workspaceSlug}/~/settings': {
      id: '/_auth/@{$workspaceSlug}/~/settings'
      path: '/~/settings'
      fullPath: '/@{$workspaceSlug}/~/settings'
      preLoaderRoute: typeof AuthAtChar123workspaceSlugChar125Char126SettingsRouteImport
      parentRoute: typeof AuthAtChar123workspaceSlugChar125Route
    }
    '/_auth/@{$workspaceSlug}/~/members': {
      id: '/_auth/@{$workspaceSlug}/~/members'
      path: '/~/members'
      fullPath: '/@{$workspaceSlug}/~/members'
      preLoaderRoute: typeof AuthAtChar123workspaceSlugChar125Char126MembersRouteImport
      parentRoute: typeof AuthAtChar123workspaceSlugChar125Route
    }
    '/_auth/@{$workspaceSlug}/~/billing': {
      id: '/_auth/@{$workspaceSlug}/~/billing'
      path: '/~/billing'
      fullPath: '/@{$workspaceSlug}/~/billing'
      preLoaderRoute: typeof AuthAtChar123workspaceSlugChar125Char126BillingRouteImport
      parentRoute: typeof AuthAtChar123workspaceSlugChar125Route
    }
    '/_auth/@{$workspaceSlug}/$resourceSlug/~/settings': {
      id: '/_auth/@{$workspaceSlug}/$resourceSlug/~/settings'
      path: '/~/settings'
      fullPath: '/@{$workspaceSlug}/$resourceSlug/~/settings'
      preLoaderRoute: typeof AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRouteImport
      parentRoute: typeof AuthAtChar123workspaceSlugChar125ResourceSlugRoute
    }
  }
}

interface AuthAtChar123workspaceSlugChar125ResourceSlugRouteChildren {
  AuthAtChar123workspaceSlugChar125ResourceSlugIndexRoute: typeof AuthAtChar123workspaceSlugChar125ResourceSlugIndexRoute
  AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRoute: typeof AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRoute
}

const AuthAtChar123workspaceSlugChar125ResourceSlugRouteChildren: AuthAtChar123workspaceSlugChar125ResourceSlugRouteChildren =
  {
    AuthAtChar123workspaceSlugChar125ResourceSlugIndexRoute:
      AuthAtChar123workspaceSlugChar125ResourceSlugIndexRoute,
    AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRoute:
      AuthAtChar123workspaceSlugChar125ResourceSlugChar126SettingsRoute,
  }

const AuthAtChar123workspaceSlugChar125ResourceSlugRouteWithChildren =
  AuthAtChar123workspaceSlugChar125ResourceSlugRoute._addFileChildren(
    AuthAtChar123workspaceSlugChar125ResourceSlugRouteChildren,
  )

interface AuthAtChar123workspaceSlugChar125RouteChildren {
  AuthAtChar123workspaceSlugChar125ResourceSlugRoute: typeof AuthAtChar123workspaceSlugChar125ResourceSlugRouteWithChildren
  AuthAtChar123workspaceSlugChar125IndexRoute: typeof AuthAtChar123workspaceSlugChar125IndexRoute
  AuthAtChar123workspaceSlugChar125Char126BillingRoute: typeof AuthAtChar123workspaceSlugChar125Char126BillingRoute
  AuthAtChar123workspaceSlugChar125Char126MembersRoute: typeof AuthAtChar123workspaceSlugChar125Char126MembersRoute
  AuthAtChar123workspaceSlugChar125Char126SettingsRoute: typeof AuthAtChar123workspaceSlugChar125Char126SettingsRoute
}

const AuthAtChar123workspaceSlugChar125RouteChildren: AuthAtChar123workspaceSlugChar125RouteChildren =
  {
    AuthAtChar123workspaceSlugChar125ResourceSlugRoute:
      AuthAtChar123workspaceSlugChar125ResourceSlugRouteWithChildren,
    AuthAtChar123workspaceSlugChar125IndexRoute:
      AuthAtChar123workspaceSlugChar125IndexRoute,
    AuthAtChar123workspaceSlugChar125Char126BillingRoute:
      AuthAtChar123workspaceSlugChar125Char126BillingRoute,
    AuthAtChar123workspaceSlugChar125Char126MembersRoute:
      AuthAtChar123workspaceSlugChar125Char126MembersRoute,
    AuthAtChar123workspaceSlugChar125Char126SettingsRoute:
      AuthAtChar123workspaceSlugChar125Char126SettingsRoute,
  }

const AuthAtChar123workspaceSlugChar125RouteWithChildren =
  AuthAtChar123workspaceSlugChar125Route._addFileChildren(
    AuthAtChar123workspaceSlugChar125RouteChildren,
  )

interface AuthRouteChildren {
  AuthAtChar123workspaceSlugChar125Route: typeof AuthAtChar123workspaceSlugChar125RouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthOrganizationsIndexRoute: typeof AuthOrganizationsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAtChar123workspaceSlugChar125Route:
    AuthAtChar123workspaceSlugChar125RouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthOrganizationsIndexRoute: AuthOrganizationsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
